oracle:
  user: "APPUSER"
  password: "appuser123#"
  host: "10.6.46.17"
  port: 1521
  service: "HTEST01"
  proxy_schema: "REPORTES"
  connection_timeout: "30"

api:
  token: tu_token_seguro
  allowed_ips:
    - 127.0.0.1
    - ::1
    - localhost
  no_auth: false

server:
  port: 8080
